version: '3'

services:
  sqlserver:
    container_name: onboarding.tutorial.sqlserver.tests
    image: microsoft/mssql-server-linux
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=DefaultPassword1
      - MSSQL_PID=Developer
    ports:
      - "1433:1433"
    networks:
      - fs_network
networks:
  fs_network:
    driver: bridge